language: R
sudo: false
cache: packages
warnings_are_errors: true


before_install:
  - export NEUROC_TRAVIS_KEY=asdf
  - export NEUROC_APPVEYOR_KEY=asdf
  - export NEUROC_DEVEL_TRAVIS_KEY=asdf
  - export NEUROC_DEVEL_APPVEYOR_KEY=asdf 
  - export NEUROC_RELEASE_TRAVIS_KEY=asdf
  - export NEUROC_RELEASE_APPVEYOR_KEY=asdf
  - export NEUROC_DEVEL_RELEASE_TRAVIS_KEY=asdf
  - export NEUROC_DEVEL_RELEASE_APPVEYOR_KEY=asdf  
  - export OSLER_TRAVIS_KEY=asdf
  - export OSLER_APPVEYOR_KEY=asdf
  - export OSLER_DEVEL_TRAVIS_KEY=asdf
  - export OSLER_DEVEL_APPVEYOR_KEY=asdf 
  - export OSLER_RELEASE_TRAVIS_KEY=asdf
  - export OSLER_RELEASE_APPVEYOR_KEY=asdf
  - export OSLER_DEVEL_RELEASE_TRAVIS_KEY=asdf
  - export OSLER_DEVEL_RELEASE_APPVEYOR_KEY=asdf    

env: 
  - user=neuroconductor

matrix:
  include:
    - env: 
      - dev=FALSE
      - deployment=FALSE
    - env: 
      - dev=TRUE
      - deployment=FALSE      
    - env: 
      - dev=TRUE
      - deployment=TRUE  


script:
  - Rscript -e 'remotes::install_github("muschellij2/neuroc.deps")'
  - export pkg=stapler
  - git clone --depth=1 https://github.com/muschellij2/${pkg}
  - cd ${pkg}
  - str="neuroc.deps::use_neuroc_template(deployment = ${deployment}, dev = ${dev})"; Rscript -e "${str}"



notifications:
  email:
    on_success: change
    on_failure: change
